server:
  port: 8090
spring:
  application:
    name: service-producer
eureka:
  client:
    # 设置注册中心地址，默认是 http://localhost:8761/eureka/
    # 这里的 peer1、peer2、peer3 是副本节点，需要在hosts里设置，如“ 127.0.0.1 peer1”
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/